import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "animate.css";
const inter = Inter({ subsets: ["latin"] });
import { SWRConfig } from "swr";

export const metadata: Metadata = {
  title: "Pokedex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + "bg-slate-100"}>{children}</body>
    </html>
  );
}
